# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1560Q2Zwjq89wjA-a6bVIh3gkWSw_c_FY
"""

import numpy as np
import matplotlib.pyplot as plt

# Constants
P_atm = 101325  # Atmospheric pressure in Pascals (1 atm)
m_piston = 5.0  # Mass of the piston (kg)
g = 9.81        # Gravitational acceleration (m/s^2)
A = 0.01        # Cross-sectional area of the piston (m^2)
V0 = 0.001      # Initial volume inside the cylinder (m^3)
n = 0.01        # Moles of gas in the cylinder
R = 8.314       # Universal gas constant (J/mol/K)
T = 300         # Temperature in Kelvin (assumed constant)

# Time simulation parameters
time_steps = 100
t = np.linspace(0, 10, time_steps)  # Time from 0 to 10 seconds

# Piston height (linearly increasing for simplicity)
h = np.linspace(0, 0.1, time_steps)  # Height from 0 to 10 cm (0.1 m)
V = V0 + A * h  # Volume as a function of height

# Pressure calculation using ideal gas law
P = (n * R * T) / V  # P = nRT / V

# Add atmospheric pressure and piston weight
P_total = P + P_atm + (m_piston * g) / A

# Plot results
plt.figure(figsize=(10, 6))
plt.plot(t, P_total, label='Total Pressure (P_total)')
plt.plot(t, P, label='Gas Pressure (P_gas)', linestyle='--')
plt.axhline(P_atm, color='r', linestyle=':', label='Atmospheric Pressure (P_atm)')
plt.xlabel('Time (s)')
plt.ylabel('Pressure (Pa)')
plt.title('Pressure Simulation During Piston Release')
plt.legend()
plt.grid(True)
plt.show()